### ISSUE TITLE
Firmware bug with CW1200

### ISSUE THREAD

**Issue by jmichelp** [newaetech/chipwhisperer#133]
There's a firmware issue on the CW1200 that crashes part of the device (e.g. the USB doesn't answer, the touch screen doesn't work anymore but the status LED is still blinking) when trying to reconnect the scope.

Steps to reproduce are fairly easy:
* connect to any target
* disconnect the scope (scope.dis())
* reconnect the scope (scope.con())

This will result in a Broken pipe error message due a USB control transfer failing when initializing OpenADC (_OpenADCInterface.py", line 1674, in sendMessage).
The only solution is to physically disconnect the power cable to restart the device.

**Comment by colinoflynn** [comment]
Does the status LED stop blinking?

Is this related to recent CW-Capture changes at all? I know you use to be able to do just that, but it could be a FW bug that wasn't triggered.

Does closing/reopening CW-Capture do anything (i.e., so it clears any old USB connections hanging around).

**Comment by jmichelp** [comment]
Status LED is still blinking after the crash.

Closing CW-Capture and restarting it doesn't help. It actually produces the same effect through scripting. That's why I was assuming a crash on the firmware (especially considering the touch screen doesn't work until I power cycle the device).

If PR #131 have a role here it's only by triggering the bug more often: before this patch, the UI was not disconnecting the scope/target and now it does it systematically.

I also tried to add some code to reset the USB device but it wasn't solving the issue.

I haven't tried yet with a CW-lite but I'm pretty sure it will work. My scripts haven't changed over the last month, only the hardware did.

**Comment by jmichelp** [comment]
OS: Linux Debian

As I mentioned before the problem occurs both in script and in the GUI (i.e. if I connect everything on the GUI, then click "Scope" to disconnect it, any further attempt to connect it back fails with an exception on libusb). Creating a standalone script doing scope.dis() scope.con() has the exact same result.

I can confirm later this week that the same script on the same machine with my CW-lite works fine if that helps.

**Comment by jmichelp** [comment]
In case this plays any role: the CW is connected to a USB3.0 controller. I know it's a USB2 device but maybe the controller send extra USB frames that the device doesn't handle properly.

I can also make a capture at USB level to see the packets and what's going wrong at USB level.

**Comment by colinoflynn** [comment]
Quick update - were able to recreate it with a script here, haven't had a chance to put a debugger on it but hopefully can fix it on one side or the other (Python SW or firmware)

**Comment by colinoflynn** [comment]
I hope we've fixed what caused this in commit 3ab8024 . Basically root causes are:

1. CW uses a lock when read/writing to FPGA. This is most noticeable on the CW-Pro as it needs it to ensure LCD refresh (which reads value from FPGA) doesn't mess with USB transactions.
2. This lock + the associated USB bulk transfer endpoint setup are done only with a USB "set configuration" command happens. This is normally part of the either soft reset or regular USB connection, so a good time to throw away anything old and set everything up again.
3. As it turns out, calling set_configuration() from pyusb didn't actually cause this to happen if the USB stack had already put the device into that configuration. I assumed it would resend the set_configuration request anyway, which would set things back up as expected on reconnect. Adding a set_configuration(0) explicitly sets the device into a different (unconfigured/reset) state.

Let me know if this works & can close the issue!

**Comment by jmichelp** [comment]
Works perfectly. Thanks for fixing this.
