### ISSUE TITLE
Why are you not closing or merging PRs?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [newaetech/chipwhisperer#151]
I'm a bit concerned that after having bought a CW Lite that the github repo does not seem to be getting any attention.

You have PR's that are 9 months old or more, which are still open but with no comments.

I've forked the repo and may pull / merge these PR's into my own fork, but its unclear whether any of them have problems, because there aren't any replies from newaetech

**Comment by colinoflynn** [comment]
I'm not sure the issue here - the entire idea of FOSS is that you can freely decide to merge in your own changes, and aren't reliant on us to make such changes.

There is a lot of various supported HW, and we're often slow to merge stuff in as testing can take some time (especially FPGA changes which require a long build process). The nature of the project makes doing proper automated testing difficult, as haven't had time to set up a full test server. Sometimes PR languish by accident too (or if several of us travelling etc). We normally get to those eventually, but if people externally have any comments/test reports can be helpful...
