### ISSUE TITLE
CW capture in Release 4.0 is quite different to the one in github master

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [newaetech/chipwhisperer#157]
Because CW Capture in Release 4.0 has a null scope object, I've tried running the CW Capture from the master branch of the repo

However it does not contain the "Capture 1" or "Capture M" or multiple other buttons, also the "ChipWhisperer" tab in the bottom center of the UI, only contains 3 scripts

(trying to run the scripts from the FileSystem tab mostly fails

Of the 3 scripts visible, attack_des.py also won't run

**Comment by colinoflynn** [comment]
The switch to 4.0 has broken some stuff, so right now 'develop' is the most up-to-date. I can't remember if 4.0.1 was pushed to master, but normally we are trying to keep stable releases on master.

None of the issues you mention are "fixable" since you are referencing an old version and various fixes are/will be pushed into develop, I'm not sure what the issue is besides possibly needing an updated release (with associated master update). Closed issue  - if you have general comments forum.newae.com is more appropriate.
