### ISSUE TITLE
Updating preprocessing module causes plot command to change

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#31]
Updating preprocessing module sets plot command as default

**Comment by gregdeon** [comment]
I looked into this today. The problem is that the preprocessing modules are stored in a dictionary (to help with the dropdown menus), so only one module of each kind can be saved for these menus. Then, the automated script's setup routines cause the new preprocessing module to be replaced with another one dedicated for the automated script. Finally, the waveform widget can't find the right module in the list, so it switches back to None temporarily, resetting the plot command.
